//! 17: Tileset sprites -- real pixel art in the same grid, with a glyph fallback.
//!
//! Every other demo in this gallery draws terrain with characters. This one
//! swaps in a PNG sprite sheet for the same tiles and changes nothing else:
//! the map, the camera, the picking, and the layout are identical, because a
//! sprite is just another thing a cell can contain. That is the Dwarf
//! Fortress and Caves of Qud architecture, where the glyph grid stays
//! authoritative and graphics are a presentation layer over it.
//!
//! Techniques on show:
//!
//! - **Sprite sheet loading** ([`TilesetOptions`]): a PNG cut into 16x16 tiles,
//!   each mapped to a Unicode private-use codepoint (`U+E000` onward) so a
//!   sprite is addressed exactly like any other character. Generated by
//!   `cargo run -p gen-tileset`, so the asset is reproducible and
//!   license-clean rather than vendored art.
//! - **Graceful degradation**: the sprite codepoints are meaningless on a
//!   terminal, so the demo keeps a parallel ASCII mapping and picks between
//!   them at draw time. Press `G` to switch and watch the same map redraw in
//!   the other idiom.
//! - **Layered compositing**: terrain sprites on layer 0, settlement sprites
//!   on layer 1, so a town's transparent corners alpha-blend against the
//!   terrain drawn beneath rather than punching a hole in it.
//!
//! Tilesets are a `retroglyph-software` / `retroglyph-gl` capability: pixel
//! backends only. On crossterm and headless this demo runs the ASCII path
//! automatically, which is the entire point of keeping both.
//!
//! ```sh
//! cargo run --example 17_tileset_sprites --features software  # sprites
//! cargo run --example 17_tileset_sprites --features gl        # sprites
//! cargo run --example 17_tileset_sprites --features crossterm # ASCII fallback
//! cargo run --example 17_tileset_sprites                      # headless
//! ```

use retroglyph_core::event::{Event, KeyCode, MouseButton, MouseEventKind};
use retroglyph_core::{Backend, Color, Frame, Style, Terminal};

use ascii_tile_demos::ui::{self, PrintStr};
use ascii_tile_demos::util::perf::FpsMeter;
use ascii_tile_demos::{Demo, GRID_COLS, GRID_ROWS};
use tilekit::camera::TileCamera;
use tilekit::geom::{Cell, SquareLayout, Tile};
use tilekit::palette::{self, mix, scale};
use tilekit::world::{Biome, Site, World};

/// World size in cells.
const WORLD_W: i32 = 200;
/// See [`WORLD_W`].
const WORLD_H: i32 = 130;

/// Cells per tile. A sprite is 16x16 pixels and the embedded font cell is
/// 8x16, so one sprite covers exactly 2x1 cells; a tile is a 2x1 block so
/// sprite and tile line up one to one with no scaling.
const TILE: SquareLayout = SquareLayout { w: 2, h: 1 };

/// First sprite codepoint. Must match `FIRST_CODEPOINT` in
/// `tools/gen-tileset/src/main.rs`; the manifest that tool prints on every run
/// is the thing to check this against.
const SPRITE_BASE: u32 = 0xE000;

/// Sprite indices, in sheet order. Duplicated from the generator's `SPRITES`
/// table because a `[[example]]` target cannot import from a `tools/` binary
/// crate; the generator prints a manifest specifically so this stays checkable
/// by eye, and [`sprite_for`] is unit-tested against the count.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
enum SpriteId {
    Ocean = 0,
    Shallows = 1,
    Sand = 2,
    Grass = 3,
    Forest = 4,
    Conifer = 5,
    Hills = 6,
    Mountain = 7,
    Snow = 8,
    Desert = 9,
    Town = 10,
    Keep = 11,
}

/// Number of sprites in the sheet. Referenced by the tests that guard the
/// biome-to-sprite mapping against the sheet running out of art.
#[allow(dead_code, reason = "only referenced from the test module")]
const SPRITE_COUNT: u32 = 12;

impl SpriteId {
    /// The private-use character this sprite is addressed by.
    fn glyph(self) -> char {
        char::from_u32(SPRITE_BASE + self as u32).unwrap_or('?')
    }
}

/// The sprite that stands in for a biome.
///
/// A deliberate lossy mapping: the world has sixteen biomes and the sheet has
/// twelve sprites, because hand-drawn terrain art is expensive and a savanna
/// drawn as grass is a much smaller lie than a savanna drawn as a question
/// mark. Real tileset games make exactly this compromise, then paint over it
/// with color modulation, which is what [`biome_tint`] does here.
const fn sprite_for(biome: Biome) -> SpriteId {
    match biome {
        Biome::Ocean => SpriteId::Ocean,
        Biome::Sea | Biome::Lake => SpriteId::Shallows,
        Biome::Coast => SpriteId::Sand,
        Biome::Grassland | Biome::Savanna | Biome::Marsh => SpriteId::Grass,
        Biome::Forest | Biome::Jungle => SpriteId::Forest,
        Biome::Taiga => SpriteId::Conifer,
        Biome::Scrubland | Biome::Tundra => SpriteId::Hills,
        Biome::Mountain => SpriteId::Mountain,
        Biome::Peak | Biome::Ice => SpriteId::Snow,
        Biome::Desert => SpriteId::Desert,
    }
}

/// The sprite for a settlement.
const fn sprite_for_site(site: Site) -> Option<SpriteId> {
    match site {
        Site::Capital | Site::City | Site::Town => Some(SpriteId::Town),
        Site::Fort => Some(SpriteId::Keep),
        // Ruins, mines, and shrines have no art in the sheet; drawing them as
        // a town would be worse than leaving them to the glyph layer.
        _ => None,
    }
}

/// A per-biome tint applied over its sprite, recovering the biome distinctions
/// the twelve-sprite sheet collapses.
///
/// Returns `None` for biomes whose sprite is already exactly right, so the art
/// shows through untouched wherever it can.
const fn biome_tint(biome: Biome) -> Option<(Color, f32)> {
    match biome {
        Biome::Savanna => Some((palette::rgb(196, 176, 92), 0.42)),
        Biome::Marsh => Some((palette::rgb(74, 92, 76), 0.46)),
        Biome::Jungle => Some((palette::rgb(30, 96, 44), 0.40)),
        Biome::Tundra => Some((palette::rgb(168, 172, 158), 0.44)),
        Biome::Ice => Some((palette::rgb(206, 226, 240), 0.30)),
        Biome::Lake => Some((palette::rgb(64, 116, 158), 0.30)),
        _ => None,
    }
}

/// How the map is drawn.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
enum Mode {
    /// PNG sprites. Falls back to [`Mode::Ascii`] on a backend without them.
    #[default]
    Sprites,
    /// One character per tile.
    Ascii,
}

impl Mode {
    const fn toggled(self) -> Self {
        match self {
            Self::Sprites => Self::Ascii,
            Self::Ascii => Self::Sprites,
        }
    }

    const fn label(self) -> &'static str {
        match self {
            Self::Sprites => "sprites",
            Self::Ascii => "ascii",
        }
    }
}

/// State for the tileset demo.
pub struct TilesetSprites {
    world: World,
    camera: TileCamera,
    time: f32,
    cursor: Tile,
    fps: FpsMeter,
    mode: Mode,
}

impl Default for TilesetSprites {
    fn default() -> Self {
        // Seed chosen for what the *default framing* shows, not for the
        // world as a whole. This demo opens centered on the capital at two
        // screen columns per tile, so it sees roughly 80x39 tiles; seed 12
        // put that window entirely inside an inland massif, which rendered as
        // a screen of grey and white with none of the twelve sprites the sheet
        // actually has. Seed 14 puts a coastline in frame with no biome above
        // a quarter of the view.
        let world = World::generate(WORLD_W, WORLD_H, 14);
        let (sx, sy) = world.start_position();
        let mut camera = TileCamera::new(
            i32::from(GRID_COLS),
            i32::from(GRID_ROWS),
            WORLD_W * TILE.w,
            WORLD_H * TILE.h,
        );
        camera.center_on(Cell::new(sx * TILE.w, sy * TILE.h));
        Self {
            world,
            camera,
            time: 0.0,
            cursor: Tile::new(sx, sy),
            fps: FpsMeter::new(),
            mode: Mode::default(),
        }
    }
}

impl TilesetSprites {
    fn handle_events<B: Backend>(&mut self, term: &mut Terminal<B>) -> bool {
        for event in term.drain_events() {
            if ui::is_quit(&event) {
                return false;
            }
            match event {
                Event::Key(key) if key.is_down() => {
                    let step = if key.modifiers.contains(retroglyph_core::KeyModifiers::SHIFT) {
                        12
                    } else {
                        3
                    };
                    match key.code {
                        KeyCode::Up | KeyCode::Char('w' | 'W') => self.camera.pan(0, -step),
                        KeyCode::Down | KeyCode::Char('s' | 'S') => self.camera.pan(0, step),
                        KeyCode::Left | KeyCode::Char('a' | 'A') => self.camera.pan(-step, 0),
                        KeyCode::Right | KeyCode::Char('d' | 'D') => self.camera.pan(step, 0),
                        KeyCode::Char('g' | 'G') => self.mode = self.mode.toggled(),
                        KeyCode::Char('r' | 'R') => self.reroll(),
                        _ => {}
                    }
                }
                Event::Mouse(mouse) => self.handle_mouse(mouse.kind, mouse.position),
                _ => {}
            }
        }
        true
    }

    fn reroll(&mut self) {
        self.world = World::generate(WORLD_W, WORLD_H, self.world.seed().wrapping_add(1));
        let (sx, sy) = self.world.start_position();
        self.camera.center_on(Cell::new(sx * TILE.w, sy * TILE.h));
        self.cursor = Tile::new(sx, sy);
    }

    fn handle_mouse(&mut self, kind: MouseEventKind, pos: retroglyph_core::Pos) {
        let screen = Cell::new(i32::from(pos.x), i32::from(pos.y) - 1);
        match kind {
            MouseEventKind::Moved | MouseEventKind::Down(MouseButton::Left) => {
                self.cursor = TILE.cell_to_tile(self.camera.screen_to_world(screen));
            }
            MouseEventKind::Drag(MouseButton::Left) => {
                let world = TILE.cell_to_tile(self.camera.screen_to_world(screen));
                self.camera.pan(
                    (self.cursor.col - world.col) * TILE.w,
                    (self.cursor.row - world.row) * TILE.h,
                );
            }
            MouseEventKind::ScrollUp => self.camera.pan(0, -2),
            MouseEventKind::ScrollDown => self.camera.pan(0, 2),
            _ => {}
        }
    }

    /// Whether sprites can actually be drawn.
    ///
    /// Only the pixel backends register a tileset, so on crossterm or headless
    /// the sprite codepoints would render as tofu (or as whatever the terminal
    /// makes of a private-use character, which is worse because it is
    /// unpredictable). The mode is a *request*; this is the answer.
    fn sprites_available<B: Backend>(term: &Terminal<B>) -> bool {
        // Ask the backend, not the build. `composites_layers` is true exactly
        // for the pixel backends, which are the ones that can hold a tileset;
        // cell backends flatten layers and render glyphs through a font.
        //
        // A `cfg!(feature = "software")` here would be wrong in both
        // directions. It says yes for a binary built with `software` but
        // driven headless (which is how the snapshot tests run it), so the
        // test renders private-use codepoints no font will ever have. And it
        // would say no for a future backend that gained tilesets without
        // being named in the list.
        term.backend().composites_layers()
    }

    fn effective_mode<B: Backend>(&self, term: &Terminal<B>) -> Mode {
        if Self::sprites_available(term) {
            self.mode
        } else {
            Mode::Ascii
        }
    }

    fn draw_map<B: Backend>(&mut self, term: &mut Terminal<B>, area: retroglyph_core::Rect) {
        self.camera
            .set_viewport(i32::from(area.width()), i32::from(area.height()));
        let (col_start, row_start, col_end, row_end) = self.camera.visible_tiles(TILE.w, TILE.h);
        let sprites = self.effective_mode(term) == Mode::Sprites;

        for row in row_start..row_end {
            for col in col_start..col_end {
                if !self.world.in_bounds(col, row) {
                    continue;
                }
                let origin = self
                    .camera
                    .world_to_screen(TILE.tile_to_cell(Tile::new(col, row)));
                self.draw_tile(term, area, Tile::new(col, row), origin, sprites);
            }
        }
    }

    fn draw_tile<B: Backend>(
        &self,
        term: &mut Terminal<B>,
        area: retroglyph_core::Rect,
        tile: Tile,
        origin: Cell,
        sprites: bool,
    ) {
        let (col, row) = (tile.col, tile.row);
        let biome = self.world.biome_at(col, row);
        let selected = tile == self.cursor;

        let mut color = if sprites {
            // A sprite carries its own colors, so the foreground is a
            // *modulation* of the art rather than a replacement for it: white
            // means "draw the sprite as painted".
            biome_tint(biome).map_or(palette::WHITE, |(tint, amount)| {
                mix(palette::WHITE, tint, amount)
            })
        } else {
            biome.color()
        };

        if biome.is_water() {
            let phase = self
                .time
                .mul_add(1.2, (col as f32).mul_add(0.5, row as f32 * 0.8));
            color = scale(color, phase.sin().mul_add(0.06, 0.97));
        }
        if selected {
            color = mix(color, palette::rgb(255, 240, 190), 0.45);
        }

        let bg = if sprites {
            // Sprites are opaque, so the cell background only shows through
            // their transparent pixels; keeping it dark stops those from
            // glowing.
            ui::BG
        } else {
            scale(mix(biome.color(), ui::BG, 0.62), 1.0)
        };

        let glyph = if sprites {
            sprite_for(biome).glyph()
        } else {
            biome.glyph()
        };

        // Terrain on layer 0.
        term.layer(0);
        for dy in 0..TILE.h {
            for dx in 0..TILE.w {
                let (x, y) = (origin.x + dx, origin.y + dy);
                if !in_area(area, x, y) {
                    continue;
                }
                // A sprite spans the whole tile and is anchored at its first
                // cell; the remaining cells get a blank so nothing from the
                // previous frame shows through the sprite's transparent parts.
                let cell_glyph = if dx == 0 && dy == 0 { glyph } else { ' ' };
                let sx = (i32::from(area.left()) + x) as u16;
                let sy = (i32::from(area.top()) + y) as u16;
                term.put_styled(sx, sy, cell_glyph, Style::new().fg(color).bg(bg));
            }
        }

        // Settlements on layer 1, so their transparent corners composite
        // against the terrain below instead of erasing it.
        if let Some(landmark) = self.world.landmark_at(col, row) {
            let (marker_glyph, marker_color) = if sprites {
                sprite_for_site(landmark.site).map_or_else(
                    || landmark.site.glyph_color(),
                    |sprite| (sprite.glyph(), palette::WHITE),
                )
            } else {
                landmark.site.glyph_color()
            };
            if in_area(area, origin.x, origin.y) {
                let sx = (i32::from(area.left()) + origin.x) as u16;
                let sy = (i32::from(area.top()) + origin.y) as u16;
                term.layer(1);
                term.put_styled(sx, sy, marker_glyph, Style::new().fg(marker_color));
                term.layer(0);
            }
        }
    }

    fn status<B: Backend>(&self, term: &Terminal<B>) -> String {
        let (col, row) = (self.cursor.col, self.cursor.row);
        let biome = self.world.biome_at(col, row);
        let mode = self.effective_mode(term);
        let mut parts = vec![
            format!("({col}, {row})"),
            biome.name().to_owned(),
            format!("{} sprite", sprite_name(sprite_for(biome))),
            format!("mode {}", mode.label()),
        ];
        if !Self::sprites_available(term) {
            parts.push("(no tileset on this backend)".to_owned());
        }
        if let Some(landmark) = self.world.landmark_at(col, row) {
            parts.push(landmark.name.clone());
        }
        parts.push(format!("seed {}", self.world.seed()));
        parts.join("  ")
    }
}

/// Whether `(x, y)`, in area-relative cells, is inside `area`.
const fn in_area(area: retroglyph_core::Rect, x: i32, y: i32) -> bool {
    x >= 0 && y >= 0 && x < area.width() as i32 && y < area.height() as i32
}

/// Display name for a sprite, for the status readout.
const fn sprite_name(sprite: SpriteId) -> &'static str {
    match sprite {
        SpriteId::Ocean => "ocean",
        SpriteId::Shallows => "shallows",
        SpriteId::Sand => "sand",
        SpriteId::Grass => "grass",
        SpriteId::Forest => "forest",
        SpriteId::Conifer => "conifer",
        SpriteId::Hills => "hills",
        SpriteId::Mountain => "mountain",
        SpriteId::Snow => "snow",
        SpriteId::Desert => "desert",
        SpriteId::Town => "town",
        SpriteId::Keep => "keep",
    }
}

impl Demo for TilesetSprites {
    const NAME: &'static str = "17_tileset_sprites";
    const TITLE: &'static str = "17 Tileset sprites";
    const BLURB: &'static str = "A PNG sprite sheet in the same grid, with an ASCII fallback.";

    fn keys() -> &'static [(&'static str, &'static str)] {
        &[
            ("WASD/arrows", "pan"),
            ("drag", "pan"),
            ("G", "sprites/ascii"),
            ("R", "reroll"),
        ]
    }

    /// Registers the sprite sheet on the software backend.
    ///
    /// `include_bytes!` rather than a runtime `std::fs::read`: the WASM build
    /// has no filesystem to read from, and embedding is the only way the same
    /// source works on both. It also means a missing asset is a build error
    /// rather than a runtime panic in front of a visitor.
    #[cfg(feature = "software")]
    fn configure_software(
        builder: retroglyph_software::SoftwareBackendBuilder,
    ) -> retroglyph_software::SoftwareBackendBuilder {
        use retroglyph_software::tileset::TilesetOptions;

        let png = include_bytes!("../assets/terrain.png").to_vec();
        let options = TilesetOptions::from_bytes(png)
            .tile_size(16, 16)
            .start_codepoint('\u{E000}')
            // Each 16x16 sprite covers 2x1 cells of the 8x16 font grid.
            .spacing(2, 1)
            .build()
            .expect("the generated tileset must decode");
        builder.tileset(options)
    }

    fn tick<B: Backend>(&mut self, term: &mut Terminal<B>, frame: &Frame) -> bool {
        self.time += frame.delta.as_secs_f32();
        self.fps.record(frame.delta);
        if !self.handle_events(term) {
            return false;
        }

        let (title, content, status) = ui::split_chrome(term.area());
        term.layer(0);
        ui::fill(term, content, Style::new().bg(ui::BG));
        self.draw_map(term, content);
        term.layer(0);
        ui::title_bar::<B, Self>(term, title);
        let text = self.status(term);
        ui::status_bar::<B, Self>(term, status, &text, &self.fps);
        let _ = |t: &mut Terminal<B>| t.print_styled_str(0, 0, "", Style::new());

        term.present().ok();
        true
    }
}

ascii_tile_demos::demo_main!(TilesetSprites);

#[cfg(test)]
mod tests {
    use super::{Mode, SPRITE_BASE, SPRITE_COUNT, SpriteId, sprite_for, sprite_for_site};
    use tilekit::world::{Biome, Site};

    #[test]
    fn every_biome_maps_to_a_sprite_inside_the_sheet() {
        for biome in Biome::ALL {
            let index = sprite_for(biome) as u32;
            assert!(
                index < SPRITE_COUNT,
                "{biome:?} maps to sprite {index}, past the end of the sheet"
            );
        }
    }

    #[test]
    fn every_sprite_codepoint_is_in_the_private_use_area() {
        for index in 0..SPRITE_COUNT {
            let ch = char::from_u32(SPRITE_BASE + index).expect("valid codepoint");
            assert!(
                ('\u{E000}'..='\u{F8FF}').contains(&ch),
                "sprite {index} is outside the private use area"
            );
        }
        assert_eq!(SpriteId::Ocean.glyph(), '\u{E000}');
        assert_eq!(SpriteId::Keep.glyph(), '\u{E00B}');
    }

    #[test]
    fn settlement_sprites_only_cover_the_sites_with_art() {
        assert_eq!(sprite_for_site(Site::Capital), Some(SpriteId::Town));
        assert_eq!(sprite_for_site(Site::Fort), Some(SpriteId::Keep));
        // These deliberately have no sprite and fall back to their glyph.
        assert_eq!(sprite_for_site(Site::Ruin), None);
        assert_eq!(sprite_for_site(Site::Mine), None);
        assert_eq!(sprite_for_site(Site::Shrine), None);
    }

    #[test]
    fn water_biomes_get_water_sprites() {
        for biome in Biome::ALL.iter().filter(|b| b.is_water()) {
            let sprite = sprite_for(*biome);
            assert!(
                matches!(sprite, SpriteId::Ocean | SpriteId::Shallows),
                "{biome:?} got the non-water sprite {sprite:?}"
            );
        }
    }

    #[test]
    fn mode_toggles_and_returns() {
        assert_eq!(Mode::Sprites.toggled(), Mode::Ascii);
        assert_eq!(Mode::Ascii.toggled(), Mode::Sprites);
        assert_eq!(Mode::Sprites.toggled().toggled(), Mode::Sprites);
    }
}
