//! 58: Carved Lair -- terrain authored at runtime, and pathfinding that
//! reacts to it.
//!
//! Dungeon Keeper's whole trick is that the player *is* the level designer:
//! drag out a block to mark it for excavation, an imp walks over and chips it
//! out, the resulting hole becomes claimable floor, and floor is what rooms
//! get built on. Every other dungeon in this gallery (`24_torchlit_crypt`,
//! `35_..`, `47_hollow_talk`) is generated once before the player ever sees
//! it. This one is generated by the player, continuously, while heroes are
//! actively trying to walk through whatever is there *right now*.
//!
//! The demo opens mid-game rather than on a blank slate: a heart chamber,
//! three built rooms and a corridor network already reach out to a fixed
//! hero entrance, because a viewer's first frame should show a dungeon, not
//! a field of rock waiting for someone to start clicking. One corridor gate
//! partway along the short route starts caved in, so the long way round is
//! the only route home at first; [`CarvedLair::simulate_shortcut`] opens and
//! re-collapses that gate on its own timer, so an unattended viewer sees the
//! drawn route bend onto the shortcut and back again without ever touching
//! the keyboard.
//!
//! That second half is the commissioned element: a hero party spawns at a
//! fixed entrance and re-solves its route to the dungeon heart (or, once
//! built, the treasury) on a short timer. Dig a shortcut and the drawn route
//! visibly bends into it a beat later; wall a corridor back up and the route
//! bends away. [`tests::digging_a_shortcut_changes_the_route`] and
//! [`tests::walling_off_a_corridor_changes_the_route`] pin exactly that
//! behaviour against the same [`find_route`] the live game uses, so it is not
//! just an eyeballed effect.
//!
//! Techniques on show:
//!
//! - **A block grid sized to the live panel, not a constant**
//!   ([`CarvedLair::init`] / [`CarvedLair::ensure_grid`]): the dungeon is
//!   exactly as many blocks wide and tall as the map panel has cells, so it
//!   fills a phone screen and a desktop window equally, at whatever size each
//!   one turns out to be.
//! - **Progressive excavation** ([`Grid::dig_progress`] via [`ramp_glyph`] and
//!   [`SHADE`]): a marked block chips from solid rock down to open floor over
//!   several seconds rather than popping the instant an imp reaches it.
//! - **Territory that spreads on its own** ([`CarvedLair::simulate_claiming`]):
//!   dug floor next to already-claimed floor (or the dungeon heart) claims
//!   itself a ring at a time, the same "your influence bleeds outward" read
//!   Dungeon Keeper's imps give the crypt.
//! - **Shared pathfinding for two different walkers**
//!   ([`find_route`] over [`tilekit::path::find`]): imps routing to a marked
//!   block and heroes routing to the heart use the identical cost function,
//!   so a trap that makes heroes detour would slow an imp exactly the same
//!   way if one ever stood on it.
//! - **A drawn, live-recomputed invader route**
//!   ([`CarvedLair::simulate_heroes`] / [`CarvedLair::draw_grid`]): every
//!   hero's current path is re-solved on [`HERO_REPATH_INTERVAL`] and its
//!   remaining steps are drawn as a high-contrast line of directional arrows
//!   ([`path_glyph`]) laid over the floor, so a change in the dungeon shows
//!   up as the drawn line visibly bending, not just as the hero eventually
//!   appearing somewhere else.
//! - **A self-driven repath** ([`CarvedLair::simulate_shortcut`]): the short
//!   corridor's gate marks itself for digging, waits for the crew to open
//!   it, then caves back in on a fixed cadence -- entirely independent of
//!   player input, so the demo's whole point is visible to someone who never
//!   touches a control.
//! - **Touch-first digging** ([`ui::touch::Pointer`]): a press-and-drag in Dig
//!   mode marks a live-updating rectangle of rock as you drag, using the
//!   shared `Pointer` rather than a hand-rolled drag state machine.
//!
//! ```sh
//! cargo run --example 58_carved_lair --features crossterm
//! cargo run --example 58_carved_lair --features software
//! cargo run --example 58_carved_lair --features gl
//! cargo run --example 58_carved_lair  # headless, prints a few frames
//! ```

use retroglyph_core::event::{Event, KeyCode};
use retroglyph_core::{Backend, Color, Frame, Rect, Style, Surface, Terminal};

use ascii_tile_demos::Demo;
use ascii_tile_demos::ui::panel::{self};
use ascii_tile_demos::ui::touch::{Gesture, Hotspots, Pointer};
use ascii_tile_demos::ui::{self};
use ascii_tile_demos::util::perf::FpsMeter;
use tilekit::geom::Cell;
use tilekit::glyphs::{SHADE, ramp_glyph};
use tilekit::noise::hash01;
use tilekit::palette::{mix, rgb};
use tilekit::path::{self, Diagonals, IMPASSABLE};

/// Seconds a marked block spends fully chipping down to open floor.
///
/// Long enough that the progressive shading (see [`SHADE`]) reads as chipping
/// rather than flickering, short enough that a viewer watching one imp does
/// not lose interest before it finishes.
const DIG_TIME: f32 = 1.7;

/// Cells per second an imp walks. Faster than a hero: imps are the player's
/// own crew and should read as busier than the invaders.
const IMP_SPEED: f32 = 7.0;

/// Cells per second a hero walks.
const HERO_SPEED: f32 = 4.2;

/// How often dug-but-unclaimed floor checks its neighbours and claims itself
/// a ring outward. A fixed cadence rather than per-frame so the claim front
/// advances in visible steps -- a spreading tide, not a gradient.
const CLAIM_INTERVAL: f32 = 0.5;

/// Seconds between hero party spawns at the entrance.
const HERO_SPAWN_INTERVAL: f32 = 8.0;

/// How often a live hero re-solves its route to the current goal.
///
/// This is the cadence at which the demo proves its own premise: dig a
/// shortcut or wall one off, and within this many seconds the drawn path
/// visibly bends onto the new route. Short enough to read as reactive,
/// long enough that the path is not a jittery thing recomputed every frame.
const HERO_REPATH_INTERVAL: f32 = 0.6;

/// How long the short corridor's gate stays in one state (open or caved in)
/// before [`CarvedLair::simulate_shortcut`] flips it, in seconds.
///
/// Long enough that a viewer sees the crew actually work the gate open (a
/// few seconds of chipping) and heroes settle onto the shortcut before it
/// closes again; short enough that an unattended viewer sees at least one
/// full open/close cycle without a long wait.
const AUTO_SHORTCUT_INTERVAL: f32 = 9.0;

/// Side length of a buildable room's footprint, in blocks.
const ROOM_SIZE: i32 = 3;

/// Gold cost to build any room.
const ROOM_COST: u32 = 40;

/// Gold cost to place one trap.
const TRAP_COST: u32 = 15;

/// Number of imps working the dungeon.
const IMP_COUNT: usize = 4;

/// Starting gold, enough for one room or a couple of traps before anything
/// has been mined.
const START_GOLD: u32 = 60;

/// Rows reserved at the bottom of the content area for the action bar.
/// Exactly [`ascii_tile_demos::ui::touch::TAP_H`]: buttons at the legal
/// minimum touch height, nothing spent on a second label row a phone screen
/// cannot spare.
const ACTION_BAR_H: u16 = ui::touch::TAP_H;

/// Smallest live grid this demo will simulate. Below this a terminal is too
/// small to show a dungeon at all, and regenerating into it would just
/// thrash; the last good grid is kept on screen instead.
const MIN_COLS: i32 = 12;
/// See [`MIN_COLS`].
const MIN_ROWS: i32 = 8;

/// One block of the dungeon.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Block {
    /// Untouched solid rock.
    Rock,
    /// Rock the player has queued for excavation. See [`Grid::dig_progress`].
    Marked,
    /// Excavated but not yet claimed by the dungeon's own imps.
    Dug,
    /// Claimed floor: buildable, and already through to the dungeon's
    /// territory for pathfinding purposes.
    Claimed,
    /// A completed room.
    Room(RoomKind),
}

/// A room type the player can build on claimed floor, plus the fixed dungeon
/// heart every dungeon starts with.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum RoomKind {
    /// The dungeon's own core. Present from the start, cannot be built or
    /// filled in.
    Heart,
    Lair,
    Hatchery,
    Treasury,
    Training,
}

impl RoomKind {
    const fn label(self) -> &'static str {
        match self {
            Self::Heart => "Heart",
            Self::Lair => "Lair",
            Self::Hatchery => "Hatch",
            Self::Treasury => "Trsy",
            Self::Training => "Train",
        }
    }

    /// Base color for this room's floor tiles.
    const fn color(self) -> Color {
        match self {
            Self::Heart => rgb(150, 30, 30),
            Self::Lair => rgb(60, 90, 50),
            Self::Hatchery => rgb(120, 110, 40),
            Self::Treasury => rgb(110, 90, 20),
            Self::Training => rgb(70, 74, 84),
        }
    }

    /// A per-cell glyph that gives the room a repeating floor pattern rather
    /// than a flat color fill, so two rooms of different kinds are readable
    /// apart even in monochrome.
    const fn glyph(self, local: (i32, i32)) -> char {
        let (x, y) = local;
        match self {
            Self::Heart => '\u{2665}', // heart suit: the literal core
            Self::Lair => {
                if (x + y) % 2 == 0 {
                    '\u{2248}'
                } else {
                    '\u{00b7}'
                } // bedding
            }
            Self::Hatchery => {
                if (x * 2 + y) % 3 == 0 {
                    '\u{2666}'
                } else {
                    '\u{00b7}'
                } // eggs
            }
            Self::Treasury => {
                if (x + y * 2) % 3 == 0 {
                    '$'
                } else {
                    '\u{00b7}'
                }
            }
            Self::Training => {
                if x % 2 == 0 && y % 2 == 0 {
                    '+'
                } else {
                    '\u{00b7}'
                } // dummies on a grid
            }
        }
    }
}

/// The seven actions the action bar offers: three modes over existing floor,
/// plus one build button per non-heart [`RoomKind`].
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Mode {
    Dig,
    Fill,
    Trap,
    Build(RoomKind),
}

impl Mode {
    const fn label(self) -> &'static str {
        match self {
            Self::Dig => "Dig",
            Self::Fill => "Fill",
            Self::Trap => "Trap",
            Self::Build(kind) => kind.label(),
        }
    }

    /// The gold cost shown under this mode's button, if any.
    const fn cost(self) -> Option<u32> {
        match self {
            Self::Dig | Self::Fill => None,
            Self::Trap => Some(TRAP_COST),
            Self::Build(_) => Some(ROOM_COST),
        }
    }
}

/// Every selectable mode, in the order the action bar draws its buttons and
/// the order the `1`-`7` keys select them.
const MODES: [Mode; 7] = [
    Mode::Dig,
    Mode::Fill,
    Mode::Trap,
    Mode::Build(RoomKind::Lair),
    Mode::Build(RoomKind::Hatchery),
    Mode::Build(RoomKind::Treasury),
    Mode::Build(RoomKind::Training),
];

/// The excavatable, buildable dungeon: a `cols` x `rows` block grid plus the
/// per-block state ([`Grid::dig_progress`], gold veins, traps) that does not
/// fit in [`Block`] itself.
struct Grid {
    cols: i32,
    rows: i32,
    blocks: Vec<Block>,
    /// `0.0..1.0` chip progress for a [`Block::Marked`] cell; meaningless
    /// (and left at whatever it last was) for every other block kind.
    dig_progress: Vec<f32>,
    /// Gold still locked in an undug rock cell; 0 once mined out.
    gold_vein: Vec<f32>,
    trap: Vec<bool>,
    heart: Cell,
    entrance: Cell,
    /// `(kind, centre)` for every room [`Grid::generate`] stamps in before
    /// the player ever acts, heart included. Kept here rather than
    /// recomputed by scanning `blocks` because `generate` is the only place
    /// that decides where these go.
    starter_rooms: Vec<(RoomKind, Cell)>,
    /// The rock cells forming the short corridor's gate: caved in at first,
    /// then opened and re-collapsed by [`CarvedLair::simulate_shortcut`].
    /// Empty for grids built by hand in tests, which have no gate to toggle.
    shortcut: Vec<Cell>,
}

impl Grid {
    const fn index(&self, c: Cell) -> Option<usize> {
        if c.x < 0 || c.y < 0 || c.x >= self.cols || c.y >= self.rows {
            return None;
        }
        Some((c.y * self.cols + c.x) as usize)
    }

    fn block(&self, c: Cell) -> Block {
        self.index(c).map_or(Block::Rock, |i| self.blocks[i])
    }

    const fn is_floor(block: Block) -> bool {
        matches!(block, Block::Dug | Block::Claimed | Block::Room(_))
    }

    /// The cost to enter `c` for both imps and heroes: open floor costs 1,
    /// a trapped floor cell costs more (so a route avoids it when a
    /// cheaper detour exists, without ever making it literally impassable),
    /// and anything not yet dug out is [`IMPASSABLE`].
    ///
    /// The same function drives imp and hero movement deliberately: the
    /// module doc's claim that a trap slows anyone who walks it is only true
    /// if there is exactly one cost function for the whole dungeon.
    fn walk_cost(&self, c: Cell) -> u32 {
        let Some(i) = self.index(c) else {
            return IMPASSABLE;
        };
        if !Self::is_floor(self.blocks[i]) {
            return IMPASSABLE;
        }
        if self.trap[i] { 6 } else { 1 }
    }

    /// Carves every cell in the rectangle spanned by `(x0, y0)` and
    /// `(x1, y1)` (inclusive, order-independent, clamped to the grid) to
    /// `block`, clearing any gold vein there.
    ///
    /// The pre-authored counterpart to [`Grid::mark_rect`]: `generate` uses
    /// this to lay down the corridor network the player finds already dug,
    /// rather than a `Rock`-only variant, so it can also cut a caved-in gate
    /// back out of a corridor it just opened.
    fn carve_rect(&mut self, x0: i32, y0: i32, x1: i32, y1: i32, block: Block) {
        let (x0, x1) = (
            x0.min(x1).clamp(0, self.cols - 1),
            x0.max(x1).clamp(0, self.cols - 1),
        );
        let (y0, y1) = (
            y0.min(y1).clamp(0, self.rows - 1),
            y0.max(y1).clamp(0, self.rows - 1),
        );
        for y in y0..=y1 {
            for x in x0..=x1 {
                let Some(i) = self.index(Cell::new(x, y)) else {
                    continue;
                };
                self.gold_vein[i] = 0.0;
                self.blocks[i] = block;
            }
        }
    }

    /// Builds a dungeon that is already partway dug: solid rock studded with
    /// gold veins, but with a heart chamber, three built rooms and a
    /// corridor network already reaching a fixed hero entrance, so a viewer
    /// arrives mid-game rather than at a blank slate.
    ///
    /// The short, direct corridor between entrance and heart has one gate
    /// left caved in, so only the long way round is open at first --
    /// [`CarvedLair::simulate_shortcut`] is what digs that gate open (and
    /// later re-collapses it) without any player input.
    ///
    /// Carves the starting cavern: the dungeon heart at the centre, three
    /// starter rooms in three of the pocket's corners, and claimed floor for
    /// the rest.
    ///
    /// Split out of `generate` because that function was over clippy's
    /// 100-line ceiling, and because "what the opening cavern looks like" is
    /// the part most likely to be retuned independently of the surrounding
    /// rock and corridor carving.
    fn carve_core(&mut self, heart: Cell, core_radius: i32) {
        let near = |v: i32| (-core_radius..=-core_radius + 2).contains(&v);
        let far = |v: i32| (core_radius - 2..=core_radius).contains(&v);
        for dy in -core_radius..=core_radius {
            for dx in -core_radius..=core_radius {
                let Some(i) = self.index(heart.offset(dx, dy)) else {
                    continue;
                };
                self.gold_vein[i] = 0.0;
                self.blocks[i] = if dx.abs() <= 1 && dy.abs() <= 1 {
                    Block::Room(RoomKind::Heart)
                } else if near(dx) && near(dy) {
                    Block::Room(RoomKind::Lair)
                } else if far(dx) && near(dy) {
                    Block::Room(RoomKind::Hatchery)
                } else if near(dx) && far(dy) {
                    Block::Room(RoomKind::Training)
                } else {
                    Block::Claimed
                };
            }
        }
    }

    /// `cols`/`rows` are clamped to [`MIN_COLS`]/[`MIN_ROWS`] so every carve
    /// below always has room to work without going out of bounds, even if
    /// the caller passed a degenerate panel size.
    fn generate(seed: u32, cols: i32, rows: i32) -> Self {
        let cols = cols.max(MIN_COLS);
        let rows = rows.max(MIN_ROWS);
        let blocks = vec![Block::Rock; (cols * rows) as usize];
        let mut gold_vein = vec![0.0_f32; (cols * rows) as usize];
        let dig_progress = vec![0.0_f32; (cols * rows) as usize];
        let trap = vec![false; (cols * rows) as usize];

        for y in 0..rows {
            for x in 0..cols {
                if hash01(seed ^ 0xA17D_0001, x, y) > 0.965 {
                    let i = (y * cols + x) as usize;
                    gold_vein[i] = 30.0_f32.mul_add(hash01(seed ^ 0x60D1_0002, x, y), 15.0);
                }
            }
        }

        let heart = Cell::new(cols * 3 / 4, rows / 2);
        let entrance = Cell::new(1, rows / 2);

        // Corridor half-width and the core cavern's radius, both scaled to
        // the live grid rather than fixed, so the same generator reads as a
        // proper dungeon on a small terminal and a wide desktop window
        // alike. `core_radius` is also used below to place the three
        // starter rooms in its corners, three cells deep each.
        let half = (rows / 5).clamp(2, 8);
        let core_radius = ((rows.min(cols) - 4) / 2).clamp(4, 14);
        let corner = core_radius - 1;
        let starter_rooms = vec![
            (RoomKind::Heart, heart),
            (RoomKind::Lair, heart.offset(-corner, -corner)),
            (RoomKind::Hatchery, heart.offset(corner, -corner)),
            (RoomKind::Training, heart.offset(-corner, corner)),
        ];

        let mut grid = Self {
            cols,
            rows,
            blocks,
            dig_progress,
            gold_vein,
            trap,
            heart,
            entrance,
            starter_rooms,
            shortcut: Vec::new(),
        };

        // The long way round: entrance up to a top gallery, across, then
        // down into the core cavern. Always open -- this is the detour
        // heroes take whenever the short corridor's gate is shut.
        let top_y = (half + 1).max(2);
        let core_left = heart.x - core_radius;
        grid.carve_rect(
            entrance.x - half,
            top_y,
            entrance.x + half,
            entrance.y,
            Block::Claimed,
        );
        grid.carve_rect(
            entrance.x,
            top_y - half,
            core_left,
            top_y + half,
            Block::Claimed,
        );
        grid.carve_rect(
            core_left - half,
            top_y,
            core_left + half,
            heart.y,
            Block::Claimed,
        );

        // The short, direct corridor at the entrance/heart row, with a gate
        // near its midpoint left caved in: heroes cannot take the shortcut
        // until the gate is dug open.
        grid.carve_rect(
            entrance.x - half,
            entrance.y - half,
            core_left,
            entrance.y + half,
            Block::Claimed,
        );
        let gate_x = entrance.x + (core_left - entrance.x) / 2;
        for x in (gate_x - half)..=(gate_x + half) {
            for y in (entrance.y - half)..=(entrance.y + half) {
                let c = Cell::new(x, y);
                if let Some(i) = grid.index(c) {
                    grid.shortcut.push(c);
                    grid.blocks[i] = Block::Rock;
                }
            }
        }

        grid.carve_core(heart, core_radius);

        // The entrance itself reads as a doorway (a distinct glyph in
        // `tile_style`), not plain claimed floor.
        for dy in -1..=1 {
            let c = entrance.offset(0, dy);
            let Some(i) = grid.index(c) else { continue };
            grid.gold_vein[i] = 0.0;
            grid.blocks[i] = Block::Dug;
        }

        // A few rock cells just outside the core cavern start out already
        // marked, so an idle viewer sees the dig-claim loop (chip, open,
        // spread) running on its own from the very first frame, independent
        // of the gate's own auto-toggle.
        for &(dx, dy) in &CARDINALS {
            let c = heart.offset(dx * (core_radius + 2), dy * (core_radius + 2));
            let Some(i) = grid.index(c) else { continue };
            if grid.blocks[i] == Block::Rock {
                grid.gold_vein[i] = 0.0;
                grid.blocks[i] = Block::Marked;
            }
        }

        grid
    }

    /// Marks every [`Block::Rock`] cell in the rectangle spanned by `a` and
    /// `b` (inclusive on both ends, order-independent) for excavation.
    fn mark_rect(&mut self, a: Cell, b: Cell) {
        let (x0, x1) = (a.x.min(b.x), a.x.max(b.x));
        let (y0, y1) = (a.y.min(b.y), a.y.max(b.y));
        for y in y0..=y1 {
            for x in x0..=x1 {
                let c = Cell::new(x, y);
                if let Some(i) = self.index(c)
                    && self.blocks[i] == Block::Rock
                {
                    self.blocks[i] = Block::Marked;
                    self.dig_progress[i] = 0.0;
                }
            }
        }
    }

    /// Reverts a dug or claimed floor cell back to rock, forcing anything
    /// that was routing through it to find another way. Rooms (including the
    /// heart) refuse: filling in a finished room is not the same action as
    /// walling off a corridor and would need its own confirm step.
    fn fill_cell(&mut self, c: Cell) -> bool {
        let Some(i) = self.index(c) else { return false };
        if !matches!(self.blocks[i], Block::Dug | Block::Claimed) {
            return false;
        }
        self.blocks[i] = Block::Rock;
        self.trap[i] = false;
        true
    }

    /// Spreads claimed territory one ring outward: any [`Block::Dug`] cell
    /// cardinally touching claimed floor or a room claims itself.
    ///
    /// Mutating the same pass it reads from (rather than diffing a snapshot)
    /// means a chain of dug cells can claim more than one ring in a single
    /// call; that is a feature here, not a bug -- it is what keeps a long
    /// freshly-dug corridor from taking one tick per block to light up, and
    /// the row-major scan order keeps it exactly reproducible run to run.
    fn spread_claim(&mut self) {
        for y in 0..self.rows {
            for x in 0..self.cols {
                let c = Cell::new(x, y);
                let Some(i) = self.index(c) else { continue };
                if self.blocks[i] != Block::Dug {
                    continue;
                }
                let touches_claimed = CARDINALS.iter().any(|&(dx, dy)| {
                    matches!(
                        self.block(c.offset(dx, dy)),
                        Block::Claimed | Block::Room(_)
                    )
                });
                if touches_claimed {
                    self.blocks[i] = Block::Claimed;
                }
            }
        }
    }
}

/// The four cardinal offsets, reused for both wall-shading and
/// claim-spreading adjacency checks.
const CARDINALS: [(i32, i32); 4] = [(0, -1), (1, 0), (0, 1), (-1, 0)];

/// Finds the least-cost route from `start` to `goal` over [`Grid::walk_cost`].
///
/// One function for both imps and heroes: see the doc on
/// [`Grid::walk_cost`] for why that matters. `Diagonals::Never` because the
/// dungeon is drawn one block per cell -- a diagonal step here would visibly
/// cut a rock corner no imp actually dug through. The budget is `u32::MAX`
/// because nothing here has a turn limit; every route is either affordable in
/// full or not found at all.
fn find_route(grid: &Grid, start: Cell, goal: Cell) -> Option<path::Path> {
    path::find(
        start,
        goal,
        grid.cols,
        grid.rows,
        Diagonals::Never,
        u32::MAX,
        |c| grid.walk_cost(c),
    )
}

/// The CP437 arrow for a unit step `(dx, dy)` from one route cell to the
/// next, or a target dot for `(0, 0)` (the route's final cell, which never
/// occurs as a real step since [`find_route`] never revisits a cell).
const fn path_glyph(dx: i32, dy: i32) -> char {
    match (dx.signum(), dy.signum()) {
        (1, 0) => '\u{2192}',
        (-1, 0) => '\u{2190}',
        (0, 1) => '\u{2193}',
        (0, -1) => '\u{2191}',
        _ => '\u{25cf}',
    }
}

/// Advances a walker (imp or hero) one step along its `path`, moving `speed`
/// cells per second. Shared because imps and heroes differ only in speed and
/// in what happens once a path empties, which their own callers handle.
fn advance_path(
    pos: &mut (f32, f32),
    cell: &mut Cell,
    path: &mut Vec<Cell>,
    step: &mut usize,
    dt: f32,
    speed: f32,
) {
    if path.is_empty() {
        return;
    }
    let target = path[*step];
    let (tx, ty) = (target.x as f32, target.y as f32);
    let (dx, dy) = (tx - pos.0, ty - pos.1);
    let dist = dx.hypot(dy);
    let travel = speed * dt;
    if dist <= travel || dist < 0.001 {
        *pos = (tx, ty);
        *cell = target;
        *step += 1;
        if *step >= path.len() {
            path.clear();
            *step = 0;
        }
    } else {
        pos.0 = (dx / dist).mul_add(travel, pos.0);
        pos.1 = (dy / dist).mul_add(travel, pos.1);
    }
}

/// One of the player's own crew: walks to a marked block, chips it down to
/// floor, and picks a new target.
struct Imp {
    pos: (f32, f32),
    cell: Cell,
    path: Vec<Cell>,
    step: usize,
    /// The marked block this imp is walking to, or currently digging once
    /// `path` is empty and it has arrived adjacent to it.
    dig_target: Option<Cell>,
    /// Countdown to the next idle wander step, used only when there is
    /// nothing to dig -- see [`CarvedLair::simulate_imps`].
    wander_timer: f32,
}

/// An invading hero: walks toward the current goal (the treasury if one has
/// been built, else the heart), re-solving its route on a timer so a change
/// in the dungeon shows up as the drawn path visibly bending.
struct Hero {
    pos: (f32, f32),
    cell: Cell,
    path: Vec<Cell>,
    step: usize,
    repath_timer: f32,
}

/// State for the Carved Lair demo.
pub struct CarvedLair {
    grid: Grid,
    /// `(cols, rows)` the live grid was last generated at, so a resized panel
    /// can be detected and the dungeon regenerated to fill it.
    dims: (i32, i32),
    gold: u32,
    imps: Vec<Imp>,
    heroes: Vec<Hero>,
    /// `(kind, centre)` for every completed room, heart included at index 0.
    rooms: Vec<(RoomKind, Cell)>,
    heart_hp: f32,
    spawn_timer: f32,
    claim_timer: f32,
    /// Countdown to the next time the short corridor's gate flips between
    /// caved-in and marked-for-digging. See [`CarvedLair::simulate_shortcut`].
    shortcut_timer: f32,
    mode: Mode,
    /// Keyboard cursor, in grid coordinates, for keyboard parity with the
    /// pointer's tap-to-act.
    cursor: Cell,
    pointer: Pointer,
    hotspots: Hotspots<Mode>,
    /// A transient status-line message (e.g. "Not enough gold"), with the
    /// seconds left before it reverts to the resource readout.
    message: Option<(String, f32)>,
    time: f32,
    fps: FpsMeter,
}

impl Default for CarvedLair {
    fn default() -> Self {
        Self::new(MIN_COLS, MIN_ROWS)
    }
}

impl CarvedLair {
    const SEED: u32 = 0x4C41_1201;

    fn new(cols: i32, rows: i32) -> Self {
        let mut grid = Grid::generate(Self::SEED, cols, rows);
        let imps = Self::spawn_imps(&grid);
        let heart = grid.heart;
        let entrance = grid.entrance;
        let rooms = core::mem::take(&mut grid.starter_rooms);
        Self {
            dims: (grid.cols, grid.rows),
            rooms,
            gold: START_GOLD,
            imps,
            // One hero on screen from frame one, already mid-route: the
            // commissioned effect (a drawn, repathing invader line) must be
            // visible immediately, not only after the first spawn interval
            // elapses. `repath_timer: 0.0` makes `simulate_heroes` solve its
            // route on the very first tick.
            heroes: vec![Hero {
                pos: (entrance.x as f32, entrance.y as f32),
                cell: entrance,
                path: Vec::new(),
                step: 0,
                repath_timer: 0.0,
            }],
            heart_hp: 100.0,
            spawn_timer: 0.0,
            claim_timer: 0.0,
            shortcut_timer: 0.0,
            mode: Mode::Dig,
            // South of the heart, on plain claimed floor rather than on top
            // of the heart's own pulsing glyph, so the keyboard cursor does
            // not read as a defect in the very first frame anyone sees.
            cursor: heart.offset(0, 2),
            pointer: Pointer::new(),
            hotspots: Hotspots::new(),
            message: None,
            time: 0.0,
            fps: FpsMeter::new(),
            grid,
        }
    }

    /// Places [`IMP_COUNT`] imps on fixed offsets around the heart, clamped
    /// into the grid so a small panel never places one out of bounds.
    fn spawn_imps(grid: &Grid) -> Vec<Imp> {
        const OFFSETS: [(i32, i32); 6] = [(-2, 0), (2, 0), (0, -2), (0, 2), (-2, -2), (2, 2)];
        OFFSETS
            .iter()
            .take(IMP_COUNT)
            .map(|&(dx, dy)| {
                let c = Cell::new(
                    (grid.heart.x + dx).clamp(0, grid.cols - 1),
                    (grid.heart.y + dy).clamp(0, grid.rows - 1),
                );
                Imp {
                    pos: (c.x as f32, c.y as f32),
                    cell: c,
                    path: Vec::new(),
                    step: 0,
                    dig_target: None,
                    wander_timer: 0.0,
                }
            })
            .collect()
    }

    /// Regenerates the dungeon for a new `cols` x `rows` panel size, keeping
    /// the same seed so the terrain (gold vein placement, heart/entrance
    /// position) stays deterministic across a resize.
    fn regenerate(&mut self, cols: i32, rows: i32) {
        *self = Self::new(cols, rows);
    }

    /// Regenerates the grid if the map panel's live size has changed since
    /// the last frame. A no-op on every frame between resizes, which in
    /// practice is almost all of them.
    fn ensure_grid(&mut self, map_area: Rect) {
        let cols = i32::from(map_area.width());
        let rows = i32::from(map_area.height());
        if cols < MIN_COLS || rows < MIN_ROWS || (cols, rows) == self.dims {
            return;
        }
        self.regenerate(cols, rows);
    }

    fn handle_events<B: Backend>(&mut self, term: &mut Terminal<B>) -> bool {
        for event in term.drain_events() {
            if ui::is_quit(&event) {
                return false;
            }
            self.pointer.feed(&event);
            if let Event::Key(key) = &event
                && key.is_down()
            {
                self.handle_key(key.code);
            }
        }
        true
    }

    fn handle_key(&mut self, code: KeyCode) {
        match code {
            KeyCode::Char(c @ '1'..='7') => {
                let idx = c as usize - '1' as usize;
                if let Some(&mode) = MODES.get(idx) {
                    self.mode = mode;
                }
            }
            KeyCode::Up | KeyCode::Char('w' | 'W') => self.move_cursor(0, -1),
            KeyCode::Down | KeyCode::Char('s' | 'S') => self.move_cursor(0, 1),
            KeyCode::Left | KeyCode::Char('a' | 'A') => self.move_cursor(-1, 0),
            KeyCode::Right | KeyCode::Char('d' | 'D') => self.move_cursor(1, 0),
            KeyCode::Enter | KeyCode::Char(' ') => {
                let cursor = self.cursor;
                self.apply_action(cursor);
            }
            _ => {}
        }
    }

    const fn move_cursor(&mut self, dx: i32, dy: i32) {
        let c = self.cursor.offset(dx, dy);
        if self.grid.index(c).is_some() {
            self.cursor = c;
        }
    }

    fn set_message(&mut self, text: impl Into<String>) {
        self.message = Some((text.into(), 2.0));
    }

    /// Applies the currently selected [`Mode`] at `cell`: the shared handler
    /// for both a pointer tap and the keyboard's Enter/Space.
    fn apply_action(&mut self, cell: Cell) {
        match self.mode {
            Mode::Dig => self.grid.mark_rect(cell, cell),
            Mode::Fill => {
                if !self.grid.fill_cell(cell) {
                    self.set_message("Nothing there to fill.");
                }
            }
            Mode::Trap => self.place_trap(cell),
            Mode::Build(kind) => self.build_room(cell, kind),
        }
    }

    fn place_trap(&mut self, cell: Cell) {
        let Some(i) = self.grid.index(cell) else {
            return;
        };
        if !Grid::is_floor(self.grid.blocks[i]) || self.grid.trap[i] {
            self.set_message("Traps need clear floor.");
            return;
        }
        if self.gold < TRAP_COST {
            self.set_message("Not enough gold for a trap.");
            return;
        }
        self.grid.trap[i] = true;
        self.gold -= TRAP_COST;
    }

    fn build_room(&mut self, at: Cell, kind: RoomKind) {
        let half = ROOM_SIZE / 2;
        let mut cells = Vec::with_capacity((ROOM_SIZE * ROOM_SIZE) as usize);
        for dy in -half..=half {
            for dx in -half..=half {
                let c = at.offset(dx, dy);
                let Some(i) = self.grid.index(c) else {
                    self.set_message("Room does not fit there.");
                    return;
                };
                if self.grid.blocks[i] != Block::Claimed {
                    self.set_message("Rooms need claimed floor.");
                    return;
                }
                cells.push(i);
            }
        }
        if self.gold < ROOM_COST {
            self.set_message("Not enough gold for that room.");
            return;
        }
        self.gold -= ROOM_COST;
        for i in cells {
            self.grid.blocks[i] = Block::Room(kind);
            self.grid.trap[i] = false;
        }
        self.rooms.push((kind, at));
    }

    /// The invaders' current objective: the first built treasury, or the
    /// heart if none has been built yet.
    fn hero_goal(&self) -> Cell {
        self.rooms
            .iter()
            .find(|(kind, _)| *kind == RoomKind::Treasury)
            .or_else(|| self.rooms.first())
            .map_or(self.grid.heart, |&(_, c)| c)
    }

    fn simulate(&mut self, dt: f32) {
        self.time += dt;
        if let Some((_, ttl)) = &mut self.message {
            *ttl -= dt;
            if *ttl <= 0.0 {
                self.message = None;
            }
        }
        self.simulate_shortcut(dt);
        self.simulate_claiming(dt);
        self.simulate_imps(dt);
        self.simulate_heroes(dt);
    }

    fn simulate_claiming(&mut self, dt: f32) {
        self.claim_timer += dt;
        if self.claim_timer >= CLAIM_INTERVAL {
            self.claim_timer -= CLAIM_INTERVAL;
            self.grid.spread_claim();
        }
    }

    /// Drives the short corridor's gate through an open/close cycle on its
    /// own, with no player input, so an unattended viewer sees the drawn
    /// hero route bend onto the shortcut and back again.
    ///
    /// Queuing the gate as `Marked` (rather than carving it straight to
    /// floor) means the crew has to actually walk over and chip it, the
    /// same as any player-marked block -- the open half of the cycle is
    /// real digging, not a scripted wall-slide.
    fn simulate_shortcut(&mut self, dt: f32) {
        if self.grid.shortcut.is_empty() {
            return;
        }
        self.shortcut_timer += dt;
        if self.shortcut_timer < AUTO_SHORTCUT_INTERVAL {
            return;
        }
        self.shortcut_timer -= AUTO_SHORTCUT_INTERVAL;

        let cells = core::mem::take(&mut self.grid.shortcut);
        let open = cells.iter().all(|&c| {
            self.grid
                .index(c)
                .is_some_and(|i| Grid::is_floor(self.grid.blocks[i]))
        });
        for &c in &cells {
            let Some(i) = self.grid.index(c) else {
                continue;
            };
            if open {
                self.grid.blocks[i] = Block::Rock;
                self.grid.trap[i] = false;
                self.grid.dig_progress[i] = 0.0;
            } else if self.grid.blocks[i] == Block::Rock {
                self.grid.blocks[i] = Block::Marked;
                self.grid.dig_progress[i] = 0.0;
            }
        }
        self.grid.shortcut = cells;
    }

    fn simulate_imps(&mut self, dt: f32) {
        let assigned: Vec<Cell> = self.imps.iter().filter_map(|i| i.dig_target).collect();
        for idx in 0..self.imps.len() {
            self.step_imp(idx, dt, &assigned);
        }
    }

    /// Advances one imp: pick a marked block if idle, walk to it, chip it
    /// down, and otherwise take a small idle step so the crew reads as busy
    /// even when the player has nothing marked right now.
    fn step_imp(&mut self, idx: usize, dt: f32, assigned: &[Cell]) {
        if self.imps[idx].dig_target.is_none() && self.imps[idx].path.is_empty() {
            let from = self.imps[idx].cell;
            if let Some((target, approach)) = self.find_dig_target(from, assigned) {
                self.imps[idx].dig_target = Some(target);
                if approach != from {
                    if let Some(route) = find_route(&self.grid, from, approach) {
                        self.imps[idx].path = route.steps;
                        self.imps[idx].step = 0;
                    } else {
                        // No route after all (another imp closed it off this
                        // tick); drop the target and try again next tick.
                        self.imps[idx].dig_target = None;
                    }
                }
            } else {
                self.wander_imp(idx, dt);
                return;
            }
        }

        if !self.imps[idx].path.is_empty() {
            let (mut pos, mut cell, mut path, mut step) = (
                self.imps[idx].pos,
                self.imps[idx].cell,
                core::mem::take(&mut self.imps[idx].path),
                self.imps[idx].step,
            );
            advance_path(&mut pos, &mut cell, &mut path, &mut step, dt, IMP_SPEED);
            self.imps[idx].pos = pos;
            self.imps[idx].cell = cell;
            self.imps[idx].path = path;
            self.imps[idx].step = step;
            return;
        }

        let Some(target) = self.imps[idx].dig_target else {
            return;
        };
        if self.grid.block(target) != Block::Marked {
            self.imps[idx].dig_target = None;
            return;
        }
        let Some(gi) = self.grid.index(target) else {
            self.imps[idx].dig_target = None;
            return;
        };
        self.grid.dig_progress[gi] += dt / DIG_TIME;
        if self.grid.dig_progress[gi] >= 1.0 {
            self.grid.dig_progress[gi] = 0.0;
            self.gold += self.grid.gold_vein[gi] as u32;
            self.grid.gold_vein[gi] = 0.0;
            self.grid.blocks[gi] = Block::Dug;
            self.imps[idx].dig_target = None;
        }
    }

    /// A small deterministic idle shuffle: pick a walkable neighbour using a
    /// position/time hash rather than a stateful RNG, so idle imps still
    /// visibly move (satisfying the animation-liveness requirement even with
    /// nothing marked) without needing per-imp mutable random state.
    fn wander_imp(&mut self, idx: usize, dt: f32) {
        self.imps[idx].wander_timer -= dt;
        if self.imps[idx].wander_timer > 0.0 {
            return;
        }
        self.imps[idx].wander_timer = 1.2;
        let cell = self.imps[idx].cell;
        let tick = (self.time * 4.0) as i32;
        let roll = hash01(0xE1D0, idx as i32, tick);
        let pick = (roll * CARDINALS.len() as f32) as usize % CARDINALS.len();
        let (dx, dy) = CARDINALS[pick];
        let next = cell.offset(dx, dy);
        if self.grid.walk_cost(next) != IMPASSABLE {
            self.imps[idx].pos = (next.x as f32, next.y as f32);
            self.imps[idx].cell = next;
        }
    }

    /// Finds the nearest unassigned marked block reachable from `from`,
    /// returning it along with the floor cell an imp should approach it
    /// from. Candidates are ranked by Manhattan distance (cheap) and only the
    /// closest few are actually pathfound (expensive), which bounds the cost
    /// of a large marked area without changing which block gets picked when
    /// the nearest candidates are in fact reachable.
    fn find_dig_target(&self, from: Cell, assigned: &[Cell]) -> Option<(Cell, Cell)> {
        let mut candidates: Vec<Cell> = Vec::new();
        for y in 0..self.grid.rows {
            for x in 0..self.grid.cols {
                let c = Cell::new(x, y);
                if self.grid.block(c) == Block::Marked && !assigned.contains(&c) {
                    candidates.push(c);
                }
            }
        }
        candidates.sort_by_key(|c| (c.x - from.x).abs() + (c.y - from.y).abs());

        for target in candidates.into_iter().take(8) {
            for &(dx, dy) in &CARDINALS {
                let approach = target.offset(dx, dy);
                if approach == from {
                    return Some((target, approach));
                }
                if self.grid.walk_cost(approach) != IMPASSABLE
                    && find_route(&self.grid, from, approach).is_some()
                {
                    return Some((target, approach));
                }
            }
        }
        None
    }

    fn simulate_heroes(&mut self, dt: f32) {
        self.spawn_timer += dt;
        if self.spawn_timer >= HERO_SPAWN_INTERVAL {
            self.spawn_timer -= HERO_SPAWN_INTERVAL;
            self.heroes.push(Hero {
                pos: (self.grid.entrance.x as f32, self.grid.entrance.y as f32),
                cell: self.grid.entrance,
                path: Vec::new(),
                step: 0,
                repath_timer: 0.0,
            });
        }

        let goal = self.hero_goal();
        let mut i = 0;
        while i < self.heroes.len() {
            self.heroes[i].repath_timer -= dt;
            if self.heroes[i].repath_timer <= 0.0 {
                self.heroes[i].repath_timer = HERO_REPATH_INTERVAL;
                let from = self.heroes[i].cell;
                // Re-solved from scratch every interval regardless of whether
                // a path is already in flight: this is the recompute the
                // module doc promises. A route already under way is
                // overwritten rather than merely refreshed once empty, so a
                // newly-dug shortcut is taken immediately rather than only
                // after the hero happens to finish whatever leg it was on.
                if let Some(route) = find_route(&self.grid, from, goal) {
                    self.heroes[i].path = route.steps;
                } else {
                    self.heroes[i].path.clear();
                }
                self.heroes[i].step = 0;
            }

            let (mut pos, mut cell, mut path, mut step) = (
                self.heroes[i].pos,
                self.heroes[i].cell,
                core::mem::take(&mut self.heroes[i].path),
                self.heroes[i].step,
            );
            advance_path(&mut pos, &mut cell, &mut path, &mut step, dt, HERO_SPEED);
            self.heroes[i].pos = pos;
            self.heroes[i].cell = cell;
            self.heroes[i].path = path;
            self.heroes[i].step = step;

            if self.heroes[i].cell == goal {
                self.heart_hp = (self.heart_hp - 25.0).max(0.0);
                self.heroes.remove(i);
                continue;
            }
            i += 1;
        }
    }

    fn status_text(&self) -> String {
        if let Some((msg, _)) = &self.message {
            return msg.clone();
        }
        let built = self.rooms.len().saturating_sub(1);
        format!(
            "Gold {}  Imps {}  Rooms {built}  Heart {:.0}%  Mode: {}",
            self.gold,
            self.imps.len(),
            self.heart_hp,
            self.mode.label(),
        )
    }

    /// Converts a screen position to a grid cell, or `None` if it falls
    /// outside `map_area`.
    fn screen_to_cell(pos: retroglyph_core::Pos, map_area: Rect) -> Option<Cell> {
        if !map_area.contains_pos(pos) {
            return None;
        }
        Some(Cell::new(
            i32::from(pos.x - map_area.left()),
            i32::from(pos.y - map_area.top()),
        ))
    }

    fn handle_gesture(&mut self, gesture: Gesture, map_area: Rect) {
        if let Some(p) = gesture.tap {
            if let Some(&mode) = self.hotspots.hit(p) {
                self.mode = mode;
                return;
            }
            if let Some(cell) = Self::screen_to_cell(p, map_area) {
                self.cursor = cell;
                self.apply_action(cell);
            }
            return;
        }

        // Live drag-marking: only in Dig mode, and only once the press
        // itself did not land on a button (a drag that starts on the action
        // bar must not also paint the map underneath it).
        if self.mode != Mode::Dig {
            return;
        }
        let Some(origin) = gesture.press else { return };
        if self.hotspots.hit(origin).is_some() {
            return;
        }
        let current = gesture.drag.unwrap_or(origin);
        if let (Some(c0), Some(c1)) = (
            Self::screen_to_cell(origin, map_area),
            Self::screen_to_cell(current, map_area),
        ) {
            self.grid.mark_rect(c0, c1);
        }
    }

    fn draw_map(&self, surface: &mut Surface<'_>, area: Rect) {
        if area.width() == 0 || area.height() == 0 {
            return;
        }
        self.draw_grid(surface, area);
        self.draw_entities(surface, area);
    }

    /// Draws every block: base terrain, a heart-side edge bevel to fake side
    /// lighting spilling out of dug passages, and the current invader
    /// routes drawn as a high-contrast line of directional arrows over the
    /// floor beneath them.
    fn draw_grid(&self, surface: &mut Surface<'_>, area: Rect) {
        let mut path_dir = vec![None::<(i32, i32)>; (self.grid.cols * self.grid.rows) as usize];
        for hero in &self.heroes {
            let remaining = &hero.path[hero.step.min(hero.path.len())..];
            for pair in remaining.windows(2) {
                if let Some(i) = self.grid.index(pair[0]) {
                    path_dir[i] = Some((pair[1].x - pair[0].x, pair[1].y - pair[0].y));
                }
            }
            // The route's final cell has no "next step" to point at; mark it
            // with the target glyph instead so the line still reads as
            // ending somewhere rather than trailing off.
            if let Some(&last) = remaining.last()
                && let Some(i) = self.grid.index(last)
                && path_dir[i].is_none()
            {
                path_dir[i] = Some((0, 0));
            }
        }

        for y in 0..self.grid.rows.min(i32::from(area.height())) {
            for x in 0..self.grid.cols.min(i32::from(area.width())) {
                let c = Cell::new(x, y);
                let Some(i) = self.grid.index(c) else {
                    continue;
                };
                let (mut glyph, mut fg, mut bg) = self.tile_style(c, i);

                if let Some((dx, dy)) = path_dir[i] {
                    glyph = path_glyph(dx, dy);
                    fg = rgb(255, 244, 220);
                    bg = mix(bg, rgb(214, 58, 40), 0.72);
                }

                let at = (area.left() + x as u16, area.top() + y as u16);
                surface.put(at, glyph, Style::new().fg(fg).bg(bg));
            }
        }

        if self.grid.index(self.cursor).is_some()
            && self.cursor.x < i32::from(area.width())
            && self.cursor.y < i32::from(area.height())
        {
            let at = (
                area.left() + self.cursor.x as u16,
                area.top() + self.cursor.y as u16,
            );
            surface.put(
                at,
                '\u{25a0}',
                Style::new().fg(ui::ACCENT).bg(rgb(40, 34, 10)),
            );
        }
    }

    /// The glyph/fg/bg triple for one block, including the entrance marker
    /// and a simple cutaway edge-shade: rock next to floor is lit (light
    /// spilling from the dug passage), floor next to rock has a shadow along
    /// the wall it sits against.
    fn tile_style(&self, c: Cell, i: usize) -> (char, Color, Color) {
        let block = self.grid.blocks[i];
        match block {
            Block::Rock => {
                let lit = CARDINALS
                    .iter()
                    .any(|&(dx, dy)| Grid::is_floor(self.grid.block(c.offset(dx, dy))));
                let has_gold = self.grid.gold_vein[i] > 0.0;
                // A little per-cell tone jitter, from position alone (never
                // time), so a solid wall of rock reads as hewn stone rather
                // than a flat-filled rectangle, without breaking the
                // determinism the whole grid otherwise relies on.
                let jitter = hash01(0x2C0C, c.x, c.y) * 14.0;
                let base = if lit {
                    rgb(76 + jitter as u8, 68 + jitter as u8, 58 + jitter as u8)
                } else {
                    rgb(54 + jitter as u8, 48 + jitter as u8, 42 + jitter as u8)
                };
                if has_gold {
                    ('\u{2666}', rgb(214, 178, 90), base)
                } else {
                    ('\u{2593}', rgb(90, 82, 72), base)
                }
            }
            Block::Marked => {
                let t = self.grid.dig_progress[i];
                let glyph = ramp_glyph(&SHADE, 1.0 - t);
                let bg = mix(rgb(54, 48, 42), rgb(160, 110, 40), 0.35);
                (glyph, rgb(230, 190, 110), bg)
            }
            Block::Dug => {
                if c == self.grid.entrance {
                    ('\u{25ba}', rgb(230, 90, 80), rgb(60, 30, 26))
                } else {
                    ('\u{2591}', rgb(120, 100, 78), rgb(46, 40, 32))
                }
            }
            Block::Claimed => ('\u{00b7}', rgb(196, 150, 96), rgb(58, 42, 30)),
            Block::Room(kind) => {
                let local = (c.x.rem_euclid(ROOM_SIZE), c.y.rem_euclid(ROOM_SIZE));
                let base = kind.color();
                let bg = mix(base, rgb(10, 8, 8), 0.55);
                let fg = if kind == RoomKind::Heart {
                    let pulse = 0.5f32.mul_add((self.time * 2.2).sin(), 0.5);
                    mix(rgb(150, 40, 40), rgb(255, 120, 110), pulse)
                } else {
                    mix(base, rgb(240, 236, 220), 0.6)
                };
                (kind.glyph(local), fg, bg)
            }
        }
    }

    fn draw_entities(&self, surface: &mut Surface<'_>, area: Rect) {
        for imp in &self.imps {
            self.draw_entity(surface, area, imp.pos, '\u{0069}', rgb(120, 210, 120));
        }
        for hero in &self.heroes {
            let trapped = self
                .grid
                .index(hero.cell)
                .is_some_and(|i| self.grid.trap[i]);
            let color = if trapped {
                rgb(230, 90, 70)
            } else {
                rgb(170, 190, 230)
            };
            self.draw_entity(surface, area, hero.pos, 'H', color);
        }
    }

    fn draw_entity(
        &self,
        surface: &mut Surface<'_>,
        area: Rect,
        pos: (f32, f32),
        glyph: char,
        fg: Color,
    ) {
        let (x, y) = (pos.0.round() as i32, pos.1.round() as i32);
        if x < 0 || y < 0 || x >= i32::from(area.width()) || y >= i32::from(area.height()) {
            return;
        }
        let at = (area.left() + x as u16, area.top() + y as u16);
        let bg = match self.grid.block(Cell::new(x, y)) {
            Block::Room(kind) => mix(kind.color(), rgb(10, 8, 8), 0.55),
            Block::Claimed => rgb(58, 42, 30),
            _ => rgb(46, 40, 32),
        };
        surface.put(at, glyph, Style::new().fg(fg).bg(bg));
    }

    fn draw_action_bar(&mut self, surface: &mut Surface<'_>, area: Rect) {
        self.hotspots.clear();
        if area.width() == 0 || area.height() == 0 {
            return;
        }
        panel::band(surface, area);
        let slots = panel::columns(area, MODES.len() as u16, 1);
        for (mode, rect) in MODES.iter().copied().zip(slots) {
            if rect.width() == 0 {
                continue;
            }
            let selected = mode == self.mode;
            let bg = if selected {
                ui::ACCENT
            } else {
                panel::PANEL_BG
            };
            let fg = if selected { rgb(20, 16, 8) } else { ui::FG };
            surface.fill_rect(rect, ' ', Style::new().bg(bg));
            let label = mode.label();
            let lx = rect.left() + rect.width().saturating_sub(label.chars().count() as u16) / 2;
            surface.print((lx, rect.top() + 1), label, Style::new().fg(fg).bg(bg));
            if let Some(cost) = mode.cost() {
                let text = format!("{cost}g");
                let cx = rect.left() + rect.width().saturating_sub(text.chars().count() as u16) / 2;
                surface.print(
                    (cx, rect.top() + 2),
                    &text,
                    Style::new().fg(if selected { fg } else { ui::DIM }).bg(bg),
                );
            }
            self.hotspots.push_tappable(rect, area, mode);
        }
    }
}

impl Demo for CarvedLair {
    const NAME: &'static str = "58_carved_lair";
    const TITLE: &'static str = "Carved Lair";
    const BLURB: &'static str =
        "Dungeon Keeper: terrain dug at runtime, with invaders pathing into it.";
    const GRID: (u16, u16) = (156, 46);

    fn keys() -> &'static [(&'static str, &'static str)] {
        &[
            ("1-7", "select tool"),
            ("arrows/WASD", "move cursor"),
            ("Enter/Space", "act at cursor"),
        ]
    }

    fn init<B: Backend>(term: &mut Terminal<B>) -> Self {
        let area = term.area();
        let (_, content, _) = ui::split_chrome(area);
        let (map_area, _) = panel::split_bottom(content, ACTION_BAR_H);
        Self::new(
            i32::from(map_area.width()).max(MIN_COLS),
            i32::from(map_area.height()).max(MIN_ROWS),
        )
    }

    fn tick<B: Backend>(&mut self, term: &mut Terminal<B>, frame: &Frame) -> bool {
        // Clamped so a stalled backend (a debugger pause, a dropped frame on
        // a loaded machine) cannot hand the simulation a multi-second `dt`
        // that skips an imp clean through a wall it should have stopped at.
        let dt = frame.delta.as_secs_f32().min(0.25);
        self.fps.record(frame.delta);

        if !self.handle_events(term) {
            return false;
        }
        let gesture = self.pointer.take();

        let screen = term.area();
        let (title, content, status) = ui::split_chrome(screen);
        let (map_area, action_area) = panel::split_bottom(content, ACTION_BAR_H);
        self.ensure_grid(map_area);
        self.simulate(dt);

        let mut surface = term.surface();
        ui::fill(&mut surface, content, Style::new().bg(ui::BG));

        self.draw_map(&mut surface, map_area);
        self.draw_action_bar(&mut surface, action_area);
        self.handle_gesture(gesture, map_area);

        ui::title_bar::<Self>(&mut surface, title);
        let text = self.status_text();
        ui::status_bar::<Self>(&mut surface, status, &text, &self.fps);
        true
    }
}

ascii_tile_demos::demo_main!(CarvedLair);

#[cfg(test)]
mod tests {
    use super::{Block, Grid, find_route};
    use tilekit::geom::Cell;

    /// A hand-built grid with two possible routes between `start` and `goal`:
    /// a short one that is initially blocked by rock at `(3, 1)`, and a long
    /// one around the bottom that is always open. Digging or filling that one
    /// cell is enough to flip which route is cheapest.
    fn two_route_grid() -> (Grid, Cell, Cell) {
        let cols = 6;
        let rows = 4;
        let mut grid = Grid {
            cols,
            rows,
            blocks: vec![Block::Rock; (cols * rows) as usize],
            dig_progress: vec![0.0; (cols * rows) as usize],
            gold_vein: vec![0.0; (cols * rows) as usize],
            trap: vec![false; (cols * rows) as usize],
            heart: Cell::new(4, 1),
            entrance: Cell::new(1, 1),
            starter_rooms: Vec::new(),
            shortcut: Vec::new(),
        };
        // Open the short route along row 1, except the shortcut cell.
        for x in 0..cols {
            if x != 3 {
                let i = grid.index(Cell::new(x, 1)).unwrap();
                grid.blocks[i] = Block::Claimed;
            }
        }
        // Open the long route around the bottom (row 3) and the two columns
        // that connect row 1 to row 3 on both ends.
        for x in 0..cols {
            let i = grid.index(Cell::new(x, 3)).unwrap();
            grid.blocks[i] = Block::Claimed;
        }
        for y in 1..=3 {
            for x in [0, 5] {
                let i = grid.index(Cell::new(x, y)).unwrap();
                grid.blocks[i] = Block::Claimed;
            }
        }
        (grid, Cell::new(1, 1), Cell::new(4, 1))
    }

    #[test]
    fn digging_a_shortcut_changes_the_route() {
        let (mut grid, start, goal) = two_route_grid();
        let before = find_route(&grid, start, goal).expect("the long way round exists");
        assert!(
            !before.steps.contains(&Cell::new(3, 1)),
            "the shortcut is still rock, so the route must detour around it"
        );

        let i = grid.index(Cell::new(3, 1)).unwrap();
        grid.blocks[i] = Block::Dug;
        let after = find_route(&grid, start, goal).expect("a route still exists");

        assert_ne!(
            before.steps, after.steps,
            "opening the shortcut must change the chosen route"
        );
        assert!(
            after.steps.contains(&Cell::new(3, 1)),
            "the newly dug shortcut should now be on the route"
        );
        assert!(
            after.total_cost() < before.total_cost(),
            "the shortcut route must be cheaper than the detour"
        );
    }

    #[test]
    fn walling_off_a_corridor_changes_the_route() {
        let (mut grid, start, goal) = two_route_grid();
        let i = grid.index(Cell::new(3, 1)).unwrap();
        grid.blocks[i] = Block::Dug;
        let before = find_route(&grid, start, goal).expect("the shortcut route exists");
        assert!(before.steps.contains(&Cell::new(3, 1)));

        // Wall the shortcut back up.
        grid.blocks[i] = Block::Rock;
        let after = find_route(&grid, start, goal).expect("the long way round still exists");

        assert_ne!(
            before.steps, after.steps,
            "walling off the shortcut must change the chosen route"
        );
        assert!(
            !after.steps.contains(&Cell::new(3, 1)),
            "the walled cell must not appear on the new route"
        );
    }

    #[test]
    fn a_trap_makes_a_route_prefer_the_untrapped_detour() {
        // A dedicated layout rather than `two_route_grid`: the middle row
        // (y = 1) is a straight, trapped shortcut from start to goal; row 0
        // is a longer detour over the top that never touches the trapped
        // row except at the shared start and goal cells (which cost nothing
        // to leave). That isolation is what makes this a clean cost
        // comparison rather than a reachability one.
        let cols = 5;
        let rows = 2;
        let mut grid = Grid {
            cols,
            rows,
            blocks: vec![Block::Rock; (cols * rows) as usize],
            dig_progress: vec![0.0; (cols * rows) as usize],
            gold_vein: vec![0.0; (cols * rows) as usize],
            trap: vec![false; (cols * rows) as usize],
            heart: Cell::new(4, 1),
            entrance: Cell::new(0, 1),
            starter_rooms: Vec::new(),
            shortcut: Vec::new(),
        };
        for x in 0..cols {
            for y in 0..rows {
                let i = grid.index(Cell::new(x, y)).unwrap();
                grid.blocks[i] = Block::Claimed;
            }
        }
        let (start, goal) = (Cell::new(0, 1), Cell::new(4, 1));
        for x in 0..cols {
            let j = grid.index(Cell::new(x, 1)).unwrap();
            grid.trap[j] = true;
        }

        let route = find_route(&grid, start, goal).expect("a route exists");
        assert!(
            route.steps.iter().any(|c| c.y == 0),
            "a fully trapped shortcut should be avoided for the untrapped detour: {:?}",
            route.steps
        );
    }
}
